#version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.meta.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.meta.*,apoc.*

  # fastapi:
  #   image: chatbot-graph-rag
  #   container_name: fastapi
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - NEO4J_URI=bolt://neo4j:7687
  #     - NEO4J_USER=neo4j
  #     - NEO4J_PASSWORD=neo4j123
  #   depends_on:
  #     - neo4j